FROM golang:1.18

ARG port

ENV PORT=$port
ENV GOCONVEY=github.com/smartystreets/goconvey
ENV AIR=github.com/cosmtrek/air

EXPOSE ${PORT}

RUN apt update -y \
  && apt upgrade -y \
  && apt install -y git \
  && go install ${GOCONVEY}@latest \
  && go install ${AIR}@latest

WORKDIR /app

COPY go.mod go.sum /app/

RUN go mod vendor
RUN go mod download


COPY . .
