// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authController

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAuthController(db *gorm.DB) AuthController {
	authService := NewAuthService(db)
	authController := NewAuthController(authService)
	return authController
}
